### ISSUE TITLE
Refatorar Security

### ISSUE THREAD

**Issue by andredalpisol** [ferlicio/Projeto-BCW20-Servicos-BackEnd#26]
Renomeie os seguintes elementos do security para uma melhor descrição:

- AuthUserDetail para UserSecurityDetail;
- AuthUserDetailService para UserSecurityDetailService;
- JWTAuthenticationFilter para AuthenticationFilter;
- JWTAuthorizationFilter para AuthorizationFilter;
- JWTConfig para SecurityConfig;
- JWTUtils para TokenUtils;
Use o auxiliar de refatoração do IntelliJ

**Comment by ferlicio** [comment]
- [x] AuthUserDetail para UserSecurityDetail;
- [x] AuthUserDetailService para UserSecurityDetailService;
- [x] JWTAuthenticationFilter para AuthenticationFilter;
- [x] JWTAuthorizationFilter para AuthorizationFilter;
- [x] JWTConfig para SecurityConfig;
- [x] JWTUtils para TokenUtils;
